#!D:\Winpython\basedir27\build\winpython-2.7.10\python-2.7.10\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.numba_entry import main

if __name__ == "__main__":
    main()
